# PyTorch Fundamentals

### Pytorch tensors


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
scaler = torch.tensor(7)
scaler
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
matrix = torch.tensor([[2,3],[4,5]])
matrix

tensor([[2, 3],
        [4, 5]])

In [ ]:
matrix[1]

tensor([4, 5])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR1 = torch.tensor([[[[12,2221,22,5],[422,424,42,4]]],
                       [[[12,2221,22,5],[422,424,42,4]]]])
TENSOR1.shape

torch.Size([2, 1, 2, 4])

In [ ]:
TENSOR1.ndim

4

### Random Tensors

In [ ]:
random_tensor = torch.rand(2, 3,4)
random_tensor


tensor([[[0.3219, 0.2692, 0.5151, 0.6990],
         [0.7068, 0.2464, 0.3667, 0.2714],
         [0.6543, 0.8743, 0.4129, 0.6805]],

        [[0.6088, 0.5780, 0.7981, 0.4323],
         [0.1324, 0.1992, 0.0693, 0.7285],
         [0.2535, 0.4820, 0.5190, 0.1285]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_tensor = torch.rand(size=(224, 224, 3))

In [ ]:
random_image_tensor.ndim

3

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
  ten_zeros = torch.zeros_like(one_to_ten)
  ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [ ]:
float_tensor = torch.tensor([3,4,5],
                            dtype=None, #Defalt data type is float32
                            device = None, #It's value can be cpu or cuda
                            requires_grad = False) # To track gradients with operations on this tensor)

In [ ]:
float_tensor.dtype

torch.int64

In [ ]:
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Tensor Attribiutes

1. `tensor.dtype`
2. `tensor.device`
3. `tensor.shape`

In [ ]:
some_tensor = torch.rand(size=(3,3))
print(f"data type of the tensor is {some_tensor.dtype}")
print(f"Device the tensor is stored on is {some_tensor.device}")
print(f"shape of the tensor is {some_tensor.shape}")

data type of the tensor is torch.float32
Device the tensor is stored on is cpu
shape of the tensor is torch.Size([3, 3])


### Tensor Operations

In [ ]:
tensor = torch.tensor([1,2,4])
tensor + 10

tensor([11, 12, 14])

In [ ]:
tensor

tensor([1, 2, 4])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 40])

In [ ]:
tensor.add( 10)

tensor([11, 12, 14])



### Matrix Multiplication
1.   Element Wise Multiplication
2.   Matrix mulitplication


In [ ]:
tensor * tensor #Matrix multiplication

tensor([ 1,  4, 16])

In [ ]:
torch.matmul(tensor,tensor) # tensor @ tensor also perform same opearation

tensor(21)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)


tensor(21)
CPU times: user 1.7 ms, sys: 955 µs, total: 2.66 ms
Wall time: 7.99 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 137 µs, sys: 20 µs, total: 157 µs
Wall time: 162 µs


tensor(21)

### Tensor Aggregation (min, max, mean, sum)


In [ ]:
x = torch.arange(10,100,10)

In [ ]:
x.min(), torch.min(x)

(tensor(10), tensor(10))

In [ ]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [ ]:
x.sum() , torch.sum(x)

(tensor(450), tensor(450))

### Positional min or max (argmin, argmax)

In [ ]:
x.argmin() #Position or Index of the minimum valeu
x[0]

tensor(10)

### Reshaping, Stacking, Squeezing and Unsqeezing

In [ ]:
x = torch.arange(1,100,10)
x.shape

torch.Size([10])

In [ ]:
# Add an Extra Dimension
x_reshaped = x.reshape(1,5,2)
x_reshaped

tensor([[[ 2, 11],
         [21, 31],
         [41, 51],
         [61, 71],
         [81, 91]]])

In [ ]:
#Change view (U can still reshape the tensor but both the reshaped and original tesnor share the same memory space)
z = x.view(2,5)
z[0][0]=2
x

tensor([ 2, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) #dim = 0 (hstack)
                                             #dim = 1 (vstack)
x_stacked

tensor([[ 2,  2,  2,  2],
        [11, 11, 11, 11],
        [21, 21, 21, 21],
        [31, 31, 31, 31],
        [41, 41, 41, 41],
        [51, 51, 51, 51],
        [61, 61, 61, 61],
        [71, 71, 71, 71],
        [81, 81, 81, 81],
        [91, 91, 91, 91]])

In [ ]:
x_reshaped.shape

torch.Size([1, 5, 2])

In [ ]:
#torch.squeeze() - Remove all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape

torch.Size([5, 2])

In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specified dim
x_unsqueezed = x_squeezed.unsqueeze(dim=2)
x_unsqueezed.shape

torch.Size([5, 2, 1])

In [ ]:
#torch.permute - Rearranges the dimensions (Both shares the same memory)
x_original = torch.rand(size = (224, 224, 3))
x_permute = x_original.permute(2, 0, 1)
print(f"Original Dimensions: {x_original.shape}\n New Permuted dimensions: {x_permute.shape}")

Original Dimensions: torch.Size([224, 224, 3])
 New Permuted dimensions: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 1.1

In [ ]:
x_permute[0,0,0]

tensor(1.1000)

In [ ]:
x_original[0:10,0,:]

tensor([[1.1000, 0.1821, 0.5107],
        [0.0441, 0.6367, 0.7730],
        [0.1325, 0.2329, 0.6643],
        [0.1171, 0.8461, 0.3354],
        [0.3760, 0.5272, 0.3941],
        [0.9754, 0.2811, 0.6835],
        [0.4535, 0.5731, 0.1853],
        [0.0315, 0.9799, 0.6508],
        [0.6863, 0.9930, 0.4877],
        [0.9499, 0.3764, 0.5194]])

### Selecting Data from tensors

In [ ]:
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0] #Index on first Bracket (Outer Dimension)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] #Index on first Inner bracket

tensor([1, 2, 3])

In [ ]:
x[0][0][0], x[0][1][1]

(tensor(1), tensor(5))

In [ ]:
#Get all values of 0th and 1st dimension and 1 index value of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the o dimension but only 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
x[:,2,2], x[0,2,:]

(tensor([9]), tensor([7, 8, 9]))

### Pytorch tensors and numpy

*  Numpy Array to Tensor `torch.from_numpy(ndarray)`
*  Tensor to Numpy Array `torch.Tensor.numpy()`



In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # the default data type will be float64
array, tensor #Not shared memory

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() #data type will be float32
tensor, numpy_tensor #No shared memory

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Common Errors in Pytorch
 1.  Different dtype error
 2.  Different shape error
 3.  Differnet device error



### Reproducbility
To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

In [ ]:
RANDOM_SEED = 43
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## PyTorch GPU operations

### 1.Running tensors and Pytorch objects on the GPUs (for faster computation)

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2.Check for GPU access with pytorch

In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

### 3.Putting tensors (and models) on the GPU

GPU results in faster computations

In [ ]:
#By default tensor will be on device "cpu"
tensor = torch.tensor([2,3,4])
tensor, tensor.device

(tensor([2, 3, 4]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

### 4.Moving tensors back to CPU
   If tesnor is on GPU, can't transform it to Numpy. Numpy only work on cpu

In [ ]:
tensor_back_on_cpu = tensor.to("cpu")
numpy_array = tensor.numpy()
numpy_array

array([2, 3, 4])

## PyTorch Exercises

In [ ]:
tensor = torch.tensor([2,3,4])
li = tensor.tolist()
li

[2, 3, 4]

In [ ]:
tensor1 = torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))
result = torch.matmul(tensor1, tensor2.T)
result

tensor([[3.1524],
        [1.9502],
        [2.6647],
        [3.2763],
        [2.5918],
        [2.0225],
        [2.3451]])

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(size=(7,7))

torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(size=(1,7))
t1 @ t2.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
# gpu equivalent of torch.random_seed is torch.cuda.random_seed
torch.cuda.manual_seed(1234)


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available else "cpu"
torch.manual_seed(1234)
t_A = torch.rand(size=(2,3)).to(device)
t_B = torch.rand(size=(2,3)).to(device)
t_A, t_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
res = t_A @ t_B.T
res

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [ ]:
res.min(), torch.max(res)

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [ ]:
res.argmin(), torch.argmax(res)

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
rand_tensor = torch.rand(size=(1,1,1,10)).type(torch.float16)
rand_tensor

tensor([[[[0.5415, 0.6421, 0.2976, 0.7075, 0.4189, 0.0655, 0.8838, 0.8081,
           0.7529, 0.8989]]]], dtype=torch.float16)

In [ ]:
rand_squeezed = rand_tensor.squeeze()
print(f"1st Tensor: {rand_tensor} shape is: {rand_tensor.shape}")
print(f"2nd Tensor: {rand_squeezed} shape is: {rand_squeezed.shape}")

1st Tensor: tensor([[[[0.5415, 0.6421, 0.2976, 0.7075, 0.4189, 0.0655, 0.8838, 0.8081,
           0.7529, 0.8989]]]], dtype=torch.float16) shape is: torch.Size([1, 1, 1, 10])
2nd Tensor: tensor([0.5415, 0.6421, 0.2976, 0.7075, 0.4189, 0.0655, 0.8838, 0.8081, 0.7529,
        0.8989], dtype=torch.float16) shape is: torch.Size([10])
